export const plantsData = [
    { name: "Aloe Vera", price: 150, categories: ["Indoor", "Air Purifying"], available: true },
    { name: "Snake Plant", price: 200, categories: ["Indoor", "Air Purifying"], available: true },
    { name: "Spider Plant", price: 180, categories: ["Indoor", "Air Purifying"], available: true },
    { name: "Peace Lily", price: 220, categories: ["Indoor", "Home Decor"], available: true },
    { name: "Areca Palm", price: 400, categories: ["Indoor", "Outdoor", "Air Purifying"], available: true },
    { name: "Ficus Bonsai", price: 800, categories: ["Indoor", "Home Decor"], available: true },
    { name: "Money Plant", price: 120, categories: ["Indoor", "Home Decor"], available: true },
    { name: "ZZ Plant", price: 350, categories: ["Indoor", "Air Purifying"], available: true },
    { name: "Rubber Plant", price: 500, categories: ["Indoor", "Home Decor"], available: true },
    { name: "Croton", price: 250, categories: ["Indoor", "Outdoor"], available: true },

    { name: "Jade Plant", price: 200, categories: ["Succulent", "Indoor"], available: true },
    { name: "Haworthia", price: 180, categories: ["Succulent", "Indoor"], available: true },
    { name: "Echeveria", price: 220, categories: ["Succulent", "Home Decor"], available: true },
    { name: "Cactus Mix", price: 300, categories: ["Succulent", "Outdoor"], available: true },
    { name: "Sedum", price: 180, categories: ["Succulent"], available: true },
    { name: "Agave", price: 400, categories: ["Succulent", "Outdoor"], available: true },
    { name: "Adenium (Desert Rose)", price: 600, categories: ["Succulent", "Outdoor"], available: true },
    { name: "Kalanchoe", price: 220, categories: ["Succulent", "Indoor"], available: true },
    { name: "Lithops (Living Stones)", price: 500, categories: ["Succulent"], available: true },
    { name: "Crassula Ovata", price: 250, categories: ["Succulent", "Indoor"], available: true },

    { name: "Tulsi", price: 100, categories: ["Outdoor", "Home Decor"], available: true },
    { name: "Marigold", price: 50, categories: ["Outdoor"], available: true },
    { name: "Hibiscus", price: 150, categories: ["Outdoor", "Home Decor"], available: true },
    { name: "Bougainvillea", price: 300, categories: ["Outdoor"], available: true },
    { name: "Rose", price: 250, categories: ["Outdoor", "Home Decor"], available: true },
    { name: "Jasmine", price: 200, categories: ["Outdoor"], available: true },
    { name: "Sunflower", price: 120, categories: ["Outdoor"], available: true },
    { name: "Chrysanthemum", price: 180, categories: ["Outdoor", "Home Decor"], available: true },
    { name: "Ixora", price: 220, categories: ["Outdoor"], available: true },
    { name: "Geranium", price: 200, categories: ["Outdoor", "Home Decor"], available: true },

    { name: "Lucky Bamboo", price: 350, categories: ["Indoor", "Home Decor"], available: true },
    { name: "Philodendron", price: 280, categories: ["Indoor", "Home Decor"], available: true },
    { name: "Calathea", price: 300, categories: ["Indoor", "Home Decor"], available: true },
    { name: "Fern", price: 150, categories: ["Indoor", "Air Purifying"], available: true },
    { name: "Pothos Golden", price: 200, categories: ["Indoor", "Air Purifying"], available: true },
    { name: "Bamboo Palm", price: 500, categories: ["Indoor", "Outdoor"], available: true },
    { name: "Coleus", price: 180, categories: ["Outdoor", "Home Decor"], available: true },
    { name: "Lavender", price: 250, categories: ["Outdoor", "Home Decor"], available: true },
    { name: "Aloe Aristata", price: 220, categories: ["Succulent"], available: true },
    { name: "Opuntia (Prickly Pear Cactus)", price: 300, categories: ["Succulent", "Outdoor"], available: true },

    { name: "Fiddle Leaf Fig", price: 700, categories: ["Indoor", "Home Decor"], available: true },
    { name: "Poinsettia", price: 350, categories: ["Indoor", "Home Decor"], available: true },
    { name: "Chinese Evergreen", price: 400, categories: ["Indoor", "Air Purifying"], available: true },
    { name: "Dracaena", price: 280, categories: ["Indoor", "Air Purifying"], available: true },
    { name: "Schefflera", price: 320, categories: ["Indoor", "Outdoor"], available: true },
    { name: "Yucca", price: 450, categories: ["Outdoor", "Home Decor"], available: true },
    { name: "Banana Plant", price: 600, categories: ["Outdoor"], available: true },
    { name: "Areca Nut Palm", price: 800, categories: ["Outdoor"], available: true },
    { name: "Neem", price: 200, categories: ["Outdoor", "Air Purifying"], available: true },
    { name: "Basil Mint", price: 120, categories: ["Outdoor", "Home Decor"], available: true },
];
